spring:
  datasource:
    url: jdbc:postgresql://localhost:5431/hse_sc
    username: postgres-user
    password: postgres-password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
  cloud:
    openfeign:
      client:
        config:
          movies-info:
            url: http://www.omdbapi.com

#  h2:
#    console.enabled: true
